server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: flow-manager
  datasource:
    url: jdbc:postgresql://localhost:5434/flow-manager
    username: azaliya
    password: azaliya
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flow-manager-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 20971520
      max-request-size: 20971520

minio:
  url: http://localhost:9000
  access-key: azaliya
  secret-key: azaliya123
flow-manager:
  kafka:
    topics:
      input: input-topic
      output: output-topic
      subscription-changed: subscription-changed-topic
  minio:
    bucket: files
  shedlock:
    outbox-relay-name: outbox_relay

service:
  subscription:
     name: subscription-service

subscription:
  free:
    max-file-size: 1048576